Repository Tampere/Hanna, pull requests merged in 2022-11, with the labels that each got.

#62 Add and list projects
  .github/workflows/ci.yaml
  backend/package-lock.json
  backend/src/db.ts
  backend/src/router/index.ts
  backend/src/router/project.ts
  frontend/.devcontainer/devcontainer.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Layout.tsx
  frontend/src/components/forms/index.tsx
  frontend/src/services/notification.tsx
  frontend/src/stores/lang/en.json
  frontend/src/stores/lang/fi.json
  frontend/src/views/Project/Project.tsx
  frontend/src/views/Project/Projects.tsx
  frontend/src/views/Search.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
  shared/package-lock.json
  shared/package.json
  shared/schema/project.ts
  shared/tsconfig.json
Labels: feature

#64 Project data model additions, project view and edit form
  backend/db_migrations/0003_more-project-fields.sql
  backend/src/router/project.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Layout.tsx
  frontend/src/client.ts
  frontend/src/components/forms/index.tsx
  frontend/src/services/notification.tsx
  frontend/src/stores/lang/en.json
  frontend/src/stores/lang/fi.json
  frontend/src/views/Project/Project.tsx
  frontend/src/views/Project/Projects.tsx
  shared/schema/project.ts
Labels: feature

#63 Feature/init map
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Map/LayerDrawer.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/Zoom.tsx
  frontend/src/components/Map/mapFunctions.tsx
  frontend/src/components/Map/mapOptions.tsx
  frontend/src/stores/lang/en.json
  frontend/src/stores/lang/fi.json
  frontend/src/stores/map.ts
  frontend/src/views/Project/Project.tsx
Labels: feature

#67 Added missing dependencies
  frontend/package-lock.json
  frontend/src/views/Project/Projects.tsx
Labels: fix

#68 Updated dependencies 2022-11-03
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: chore

#69 Fixed user session identifier for AD login
  backend/src/auth.ts
Labels: fix

#71 Fixed date picker keyboard input on Chrome
  frontend/src/components/forms/index.tsx
  frontend/src/views/Project/Project.tsx
  frontend/src/views/Project/Projects.tsx
Labels: fix

#74 Fixed timezone issues in start & end date fields
  .github/workflows/ci.yaml
  backend/src/db.ts
  backend/src/router/project.ts
  frontend/src/components/forms/index.tsx
  shared/schema/project.ts
Labels: fix

#85 Fixed timestamp formatting
  frontend/src/Layout.tsx
  frontend/src/components/Map/LayerDrawer.tsx
  frontend/src/components/forms/index.tsx
  frontend/src/stores/lang/en.json
  frontend/src/stores/lang/fi.json
  frontend/src/stores/lang/index.tsx
  frontend/src/views/Project/Project.tsx
  frontend/src/views/Project/Projects.tsx
Labels: fix

#84 [deps] update packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: chore

#105 Implemented generic code selection component
  backend/db_migrations/0004_project-codes.sql
  backend/src/router/code.ts
  backend/src/router/index.ts
  e2e/test/api/code.test.ts
  e2e/test/api/project.test.ts
  e2e/tsconfig.json
  frontend/index.html
  frontend/src/components/forms/CodeSelect.tsx
  frontend/src/stores/lang/en.json
  frontend/src/stores/lang/fi.json
  frontend/src/stores/lang/index.tsx
  frontend/src/views/Profile.tsx
  frontend/src/views/Project/Projects.tsx
  shared/src/language.ts
  shared/src/schema/code.ts
Labels: feature
