Repository Tampere/Hanna, pull requests merged in 2022-10, with the labels that each got.

#43 Copy backend stuff to docker context for build process
  Dockerfile
Labels: fix

#51 Updated dependencies
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: chore

#44 Feature/hanke schema
  backend/db_migrations/0002_initial-model.sql
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/components/auth/router.ts
  backend/src/router/context.ts
  backend/src/router/createRouter.ts
  backend/src/router/index.ts
  backend/src/router/project.ts
  backend/src/router/routers/api.ts
  docker-compose.yml
  docker/db/init/10-init.sql
  docker/db/init/20-init.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Layout.tsx
  frontend/src/client.ts
  frontend/src/views/Project/Project.tsx
  frontend/src/views/Project/Projects.tsx
Labels: feature
