Repository Tampere/Hanna, pull requests merged in 2023-02, with the labels that each got.

#271 [chore] update deps
  backend/package-lock.json
  backend/package.json
  docker/oidc-provider/Dockerfile
  docker/oidc-provider/index.ts
  docker/oidc-provider/package-lock.json
  docker/oidc-provider/package.json
  docker/oidc-provider/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  shared/package-lock.json
  shared/package.json
Labels: chore

#276 Added project owner and person in charge
  backend/db_migrations/0032_project-owner-and-person-in-charge.sql
  backend/src/router/index.ts
  backend/src/router/project.ts
  backend/src/router/user.ts
  e2e/test/api/project.test.ts
  frontend/src/components/forms/CodeSelect.tsx
  frontend/src/components/forms/MultiSelect.tsx
  frontend/src/components/forms/UserSelect.tsx
  frontend/src/stores/lang/en.json
  frontend/src/stores/lang/fi.json
  frontend/src/utils/atom.ts
  frontend/src/views/Project/ProjectForm.tsx
  shared/src/schema/project.ts
Labels: feature

#277 Form server side validation and usage on project form
  backend/src/router/project.ts
  frontend/src/components/Map/MapToolbar.tsx
  frontend/src/components/forms/index.tsx
  frontend/src/stores/lang.tsx
  frontend/src/views/Profile.tsx
  frontend/src/views/Project/ProjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  shared/src/formerror.ts
  shared/src/language.ts
  shared/src/language/en.json
  shared/src/language/fi.json
  shared/src/language/index.ts
  shared/src/utils.ts
  shared/tsconfig.json
Labels: feature

#278 Add SAP actuals fetching behind feature flag
  backend/.template.env
  backend/src/components/sap/dataImport.ts
  backend/src/env.ts
Labels: feature

#279 Various fixes for preparing production release
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  frontend/src/App.tsx
  frontend/src/Layout.tsx
  frontend/src/stores/search/project.ts
  frontend/src/views/Profile.tsx
  frontend/src/views/Project/SearchControls.tsx
  frontend/src/views/Settings.tsx
Labels: fix

#280 Added person in charge to project objects
  backend/db_migrations/0033_project-object-person-in-charge.sql
  backend/src/router/projectObject.ts
  frontend/src/utils/form.ts
  frontend/src/views/ProjectObject/ProjectObjectForm.tsx
  shared/src/language/en.json
  shared/src/language/fi.json
  shared/src/schema/projectObject.ts
Labels: feature

#283 Added committees to project form and search
  backend/src/router/project.ts
  e2e/test/api/project.test.ts
  e2e/test/project.test.ts
  frontend/src/stores/search/project.ts
  frontend/src/views/Project/ProjectForm.tsx
  frontend/src/views/Project/SearchControls.tsx
  shared/src/formerror.ts
  shared/src/language/en.json
  shared/src/language/fi.json
  shared/src/schema/project.ts
Labels: feature

#310 [chore] update deps
  backend/package-lock.json
  backend/package.json
  docker/oidc-provider/package-lock.json
  docker/oidc-provider/package.json
  e2e/package-lock.json
  e2e/package.json
  frontend/package-lock.json
  frontend/package.json
  shared/package-lock.json
  shared/package.json
Labels: chore

#312 Project XLSX report from search results
  backend/db_migrations/0035_pgboss.sql
  backend/db_migrations/0036_reportfile_table.sql
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/components/report/downloadApi.ts
  backend/src/components/report/projectReport.ts
  backend/src/components/taskQueue/index.ts
  backend/src/components/taskQueue/reportQueue.ts
  backend/src/db.ts
  backend/src/router/project.ts
  backend/types/excel4node.d.ts
  frontend/src/components/AsyncJobIconButton.tsx
  frontend/src/views/Project/Projects.tsx
  shared/src/language/en.json
  shared/src/language/fi.json
  shared/src/language/index.ts
Labels: feature
