Repository Tampere/Hanna, pull requests merged in 2023-08, with the labels that each got.

#664 Added grouped update config for Dependabot
  .github/dependabot.yml
Labels: chore

#673 Added separate debit/credit columns to SAP reports
  backend/src/components/report/index.ts
  backend/src/components/sap/blanketContractReport.ts
  backend/src/components/sap/blanketContractReportQueue.ts
  backend/src/components/sap/environmentCodeReport.ts
  backend/src/components/sap/environmentCodeReportQueue.ts
  backend/src/router/sapReport.ts
  backend/types/excel4node.d.ts
  frontend/src/components/DataTable.tsx
  frontend/src/components/forms/CurrencyInput.tsx
  frontend/src/stores/sapReport/blanketContractReportFilters.ts
  frontend/src/stores/sapReport/environmentalCodeReportFilters.ts
  frontend/src/views/SapReports/BlanketContractReport.tsx
  frontend/src/views/SapReports/EnvironmentalCodeReport.tsx
  frontend/src/views/SapReports/EnvironmentalCodeReportFilters.tsx
  frontend/src/views/SapReports/ReportSummary.tsx
  shared/src/language/fi.json
  shared/src/schema/sapReport.ts
Labels: feature

#674 Added report summary to blanket contract report
  frontend/src/views/SapReports/BlanketContractReportFilters.tsx
Labels: feature

#675 Allow multiple year selections in SAP report
  backend/src/components/sap/environmentCodeReport.ts
  frontend/src/components/forms/MultiSelect.tsx
  frontend/src/stores/sapReport/environmentalCodeReportFilters.ts
  frontend/src/views/SapReports/EnvironmentalCodeReportFilters.tsx
  shared/src/schema/sapReport.ts
Labels: feature

#681 Fixed an occasional OIDC login error
  backend/src/auth.ts
Labels: fix

#698 Introduce .env file to frontend
  backend/.template.env
  frontend/.template.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/stores/search/project.ts
  frontend/vite.config.ts
Labels: chore
