Repository Tampere/Hanna, pull requests merged in 2024-05, with the labels that each got.

#1083 Disable data export button if no data is available
  frontend/src/components/LoadingButton.tsx
  frontend/src/views/SapReports/BlanketContractReport.tsx
  frontend/src/views/SapReports/BlanketContractReportFilters.tsx
  frontend/src/views/SapReports/EnvironmentalCodeReport.tsx
  frontend/src/views/SapReports/EnvironmentalCodeReportFilters.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  shared/src/language/fi.json
Labels: feature

#1082 Feature/objects to project map
  backend/src/router/projectObject.ts
  frontend/src/components/Map/LayerDrawer.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/SelectedProjectInfoBox.tsx
  frontend/src/components/Map/SelectionInfoBox/ProjectDetails.tsx
  frontend/src/components/Map/SelectionInfoBox/ProjectObjectDetails.tsx
  frontend/src/components/Map/SelectionInfoBox/StepIndicator.tsx
  frontend/src/components/Map/SelectionInfoBox/index.tsx
  frontend/src/components/Map/mapFunctions.tsx
  frontend/src/stores/map.ts
  frontend/src/stores/search/project.ts
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ProjectOwnerChangeDialog.tsx
  frontend/src/views/Project/Projects.tsx
  frontend/src/views/Project/ResultsMap.tsx
  frontend/src/views/Project/SearchControls.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/ProjectObject/ProjectObjectFormUserRoles.tsx
  frontend/src/views/WorkTable/WorkTableSummaryRow.tsx
  shared/src/language/fi.json
  shared/src/schema/projectObject.ts
Labels: feature

#1085 Fix detailplan project links and change project object filter logic f…
  backend/src/router/projectObject.ts
  e2e/utils/page.ts
  frontend/src/Layout.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/SelectionInfoBox/ProjectDetails.tsx
  frontend/src/components/Map/SelectionInfoBox/ProjectObjectDetails.tsx
  frontend/src/components/Map/SelectionInfoBox/index.tsx
  frontend/src/views/Project/Projects.tsx
  frontend/src/views/Project/ResultsMap.tsx
  shared/src/schema/projectObject.ts
Labels: fix

#1097 Log project object search
  backend/src/router/projectObject.ts
Labels: chore

#1098 Add loading skeletons to project object search
  backend/src/router/projectObject.ts
  frontend/src/views/ProjectObject/ProjectObjects.tsx
Labels: feature

#1104 Improve item search performance
  backend/src/app.ts
  backend/src/components/project/search.ts
  backend/src/components/projectObject/index.ts
Labels: feature

#1109 Update manual with reworked map content and updated images
  frontend/public/images/hankkeet_sivu_numeroitu.png
  frontend/public/images/investointiohjelmointi.png
  frontend/public/images/investointiohjelmointi_v2.png
  frontend/public/images/karttasivu.png
  frontend/public/images/karttavalinta.png
  frontend/src/views/Manual/fi.md
Labels: feature

#1110 Feature/map improvements
  backend/src/components/project/search.ts
  backend/src/components/projectObject/index.ts
  backend/src/router/project/base.ts
  frontend/src/App.tsx
  frontend/src/components/Map/LayerDrawer.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/SelectionInfoBox/ProjectObjectDetails.tsx
  frontend/src/components/Map/SelectionInfoBox/index.tsx
  frontend/src/stores/map.ts
  frontend/src/stores/useMapInfoBox.tsx
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/Projects.tsx
  frontend/src/views/Project/ResultsMap.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/ProjectObject/ProjectObjectResultsMap.tsx
  frontend/src/views/ProjectObject/ProjectObjects.tsx
  frontend/src/views/Search/index.tsx
  shared/src/schema/project/index.ts
  shared/src/schema/projectObject.ts
Labels: feature

#1111 Remove person in charge from investment projects
  backend/db_migrations/0072_drop_person_in_charge.sql
  backend/src/components/project/investment.ts
  backend/src/components/report/investmentProject.ts
  e2e/test/api/permissions.test.ts
  e2e/test/api/project.test.ts
  e2e/test/api/projectObject.test.ts
  frontend/src/views/Project/InvestmentProjectForm.tsx
  shared/src/language/fi.json
  shared/src/schema/project/investment.ts
Labels: feature

#1112 Fix hanging map feature infobox bug
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/SelectionInfoBox/ProjectObjectDetails.tsx
  frontend/src/views/Project/Projects.tsx
  frontend/src/views/ProjectObject/ProjectObjectResultsMap.tsx
  frontend/src/views/ProjectObject/ProjectObjects.tsx
Labels: fix

#1113 Add several small improvements and tweaks
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MapControls.tsx
  frontend/src/components/Map/MapToolbar.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/SelectionInfoBox/ProjectObjectDetails.tsx
  frontend/src/components/Map/mapFunctions.tsx
  frontend/src/components/Map/mapInteractions.ts
  frontend/src/components/forms/CurrencyInput.tsx
  frontend/src/components/forms/index.tsx
  frontend/src/views/Project/ProjectPermissions.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  shared/src/language/fi.json
Labels: feature
