Repository Tampere/Hanna, pull requests merged in 2024-12, with the labels that each got.

#1425 Fix/worktable search
  backend/src/router/workTable.ts
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
Labels: fix

#1426 Add clear filters button for project/object search and worktable
  frontend/src/stores/search/project.ts
  frontend/src/stores/search/projectObject.ts
  frontend/src/views/Project/SearchControls.tsx
  frontend/src/views/ProjectObject/SearchControls.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
Labels: feature

#1427 Feature/UI improvements
  backend/src/components/project/base.ts
  frontend/src/components/Map/mapOptions.tsx
  frontend/src/components/NavigationBlocker.tsx
  frontend/src/stores/map.ts
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Manual/fi.md
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/MaintenanceProjectObjectForm.tsx
  shared/src/language/fi.ts
Labels: feature

#1433 Allow investment project object moving between suitable projects
  backend/src/components/projectObject/investment.ts
  backend/src/router/projectObject/investment.ts
  e2e/test/api/project.test.ts
  e2e/test/api/projectObject.test.ts
  frontend/src/components/SplitButton.tsx
  frontend/src/views/Project/ProjectViewWrapper/ModifyButton.tsx
  frontend/src/views/Project/ProjectViewWrapper/ProjectObjectMoveView.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  shared/src/language/fi.ts
Labels: feature

#1434 Fix/bug fixes and UI improvements
  backend/src/router/workTable.ts
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
Labels: fix

#1435 Add new project object category
  backend/db_migrations/0090_new_project_object_category_3.sql
Labels: feature

#1436 Limit project object 'move' selector size
  frontend/src/views/Project/ProjectViewWrapper/ProjectObjectMoveView.tsx
Labels: feature

#1438 Remember last selected search map view when navigating between any views
  frontend/src/App.tsx
  frontend/src/Layout.tsx
  frontend/src/stores/search/searchView.ts
  frontend/src/views/Search/index.tsx
Labels: feature

#1437 Add contract price for finance charts in object view
  frontend/src/components/Charts/AmountChartHeader.tsx
  frontend/src/components/Charts/ChartHeader.tsx
  frontend/src/components/Charts/ContractPriceChartHeader.tsx
  frontend/src/components/Charts/ProgressBar.tsx
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/Project/ProjectFinancesCharts.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinancesCharts.tsx
  shared/src/language/fi.ts
Labels: feature

#1444 Feature/several small UI tweaks
  docker-compose-local.yml
  docker-compose.override.yml
  docker-compose.yml
  e2e/docker-compose.ci.yml
  e2e/docker-compose.yml
  e2e/test/login.test.ts
  frontend/src/components/SplitButton.tsx
  frontend/src/views/Project/ProjectViewWrapper/ModifyButton.tsx
  frontend/src/views/Project/ProjectViewWrapper/ProjectObjectMoveView.tsx
  frontend/src/views/Project/ProjectViewWrapper/ProjectShiftView.tsx
  shared/src/language/fi.ts
Labels: feature

#1445 Updates to manual contents and images
  frontend/public/images/kuluseuranta.png
  frontend/public/images/monilautakuntainen_talousvalilehti.png
  frontend/src/views/Manual/fi.md
Labels: chore

#1446 Add alphabetical ordering to object new project candidates selector
  backend/src/components/projectObject/investment.ts
Labels: feature

#1447 Add category and stage icons to project object list
  backend/src/components/projectObject/search.ts
  frontend/src/Layout.tsx
  frontend/src/assets/icons/hulevedet.svg
  frontend/src/assets/icons/leikkikentat.svg
  frontend/src/assets/icons/liikuntareitit.svg
  frontend/src/assets/icons/maa_ja_vesialueet.svg
  frontend/src/assets/icons/rakentaminen.svg
  frontend/src/assets/icons/satama.svg
  frontend/src/assets/icons/suunnittelu.svg
  frontend/src/assets/icons/taitorakenteet.svg
  frontend/src/assets/icons/tekniset_jarjestelmat.svg
  frontend/src/assets/icons/tiet_ja_kadut.svg
  frontend/src/assets/icons/viheralueet.svg
  frontend/src/assets/icons/ymparistorakenteet.svg
  frontend/src/assets/map/detailPlanClusterPointHover.png
  frontend/src/assets/map/detailplanClusterPoint.png
  frontend/src/assets/map/investmentClusterPoint.png
  frontend/src/assets/map/investmentClusterPointHover.png
  frontend/src/assets/map/maintenanceClusterPoint.png
  frontend/src/assets/map/maintenanceClusterPointHover.png
  frontend/src/assets/map/projectClusterPoint.png
  frontend/src/assets/map/projectClusterPointHover.png
  frontend/src/assets/map/projectClusterPointSelected.png
  frontend/src/assets/map/projectObjectClusterPoint.png
  frontend/src/assets/map/projectObjectClusterPointHover.png
  frontend/src/assets/map/projectObjectClusterPointSelected.png
  frontend/src/assets/map/projectObjectPointSmall.png
  frontend/src/components/Map/styles.ts
  frontend/src/components/forms/CodeSelect.tsx
  frontend/src/components/forms/MultiSelect.tsx
  frontend/src/components/icons/ObjectCategoryIcon.tsx
  frontend/src/components/icons/ObjectStageIcon.tsx
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
  frontend/src/views/ProjectObject/ProjectObjects.tsx
  shared/src/schema/projectObject/search.ts
Labels: feature

#1448 Enable users to save their filter selections
  backend/db_migrations/0091_user_search_filters.sql
  backend/src/components/user/index.ts
  backend/src/router/user.ts
  e2e/test/api/savedSearchFilters.test.ts
  e2e/utils/db.ts
  frontend/src/components/MultiFunctionChip.tsx
  frontend/src/components/icons/ObjectCategoryIcon.tsx
  frontend/src/components/icons/ObjectStageIcon.tsx
  frontend/src/stores/search/project.ts
  frontend/src/stores/search/projectObject.ts
  frontend/src/stores/workTable.tsx
  frontend/src/views/Project/SearchControls.tsx
  frontend/src/views/ProjectObject/SearchControls.tsx
  frontend/src/views/SavedSearchFilters.tsx
  frontend/src/views/Search/index.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  frontend/src/views/WorkTable/WorkTableSummaryRow.tsx
  shared/src/language/fi.ts
  shared/src/schema/userSavedSearchFilters.ts
Labels: feature

#1449 chore: update dependencies
  backend/package-lock.json
  backend/package.json
  e2e/package-lock.json
  e2e/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/patches/@mui+x-data-grid+7.23.2.patch
  shared/package-lock.json
  shared/package.json
Labels: chore

#1453 Update cross-spawn
  backend/package-lock.json
Labels: chore

#1459 Fix saved search filter modification bug when clicking away from filt…
  frontend/src/components/MultiFunctionChip.tsx
  frontend/src/views/SavedSearchFilters.tsx
Labels: fix

#1458 Chore/update manual with v2.5 content
  frontend/public/images/investointiohjelmointi.png
  frontend/public/images/karttasivu.png
  frontend/src/views/Manual/fi.md
Labels: chore
