Repository Tampere/Hanna, pull requests merged in 2024-02, with the labels that each got.

#953 Feature/sap company code fix and improvement
  backend/db_migrations/0061_add_trading_partner_id_to_sap_actuals.sql
  backend/src/components/report/index.ts
  backend/src/components/sap/dataImport.ts
  backend/src/components/sap/environmentCodeReport.ts
  backend/src/components/sap/environmentCodeReportQueue.ts
  backend/src/components/sap/transform.spec.ts
  backend/src/components/sap/transform.ts
  docker/sap-mock/mock-server.clj
  e2e/test/workTable.test.ts
  frontend/src/App.tsx
  frontend/src/components/DataTable/DataTableRow.tsx
  frontend/src/components/DataTable/index.tsx
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinances.tsx
  frontend/src/views/SapReports/BlanketContractReport.tsx
  frontend/src/views/SapReports/EnvironmentalCodeReport.tsx
  frontend/src/views/SapReports/EnvironmentalCodeReportFilters.tsx
  frontend/src/views/WorkTable/columns.tsx
  shared/src/language/fi.json
  shared/src/schema/sapActuals.ts
  shared/src/schema/sapReport.ts
Labels: feature

#956 Feature/worktable compacting
  frontend/src/Layout.tsx
  frontend/src/components/forms/MultiSelect.tsx
  frontend/src/views/ProjectObject/ProjectObjectForm.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  frontend/src/views/WorkTable/WorkTableFilters.tsx
  frontend/src/views/WorkTable/columns.tsx
Labels: feature

#957 Feature/several minor new features
  backend/.template.env
  backend/src/app.ts
  backend/src/env.ts
  e2e/test/project.test.ts
  e2e/test/workTable.test.ts
  frontend/src/Layout.tsx
  frontend/vite.config.ts
  shared/src/language/fi.json
  shared/src/schema/projectObject.ts
Labels: feature

#959 Change company code representation logic
  frontend/src/views/SapReports/EnvironmentalCodeReport.tsx
  shared/src/language/fi.json
Labels: fix

#960 Feature/worktable tweaks
  backend/src/components/sap/transform.ts
  docker/sap-mock/mock-server.clj
  frontend/src/Layout.tsx
  frontend/src/views/WorkTable/BackToTopButton.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
Labels: feature

#969 Feature/project object stage
  backend/db_migrations/0062_add_project_object_stage.sql
  backend/src/router/projectObject.ts
  e2e/test/api/projectObject.test.ts
  frontend/src/Layout.tsx
  frontend/src/views/ProjectObject/ProjectObjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  shared/src/language/fi.json
  shared/src/schema/code.ts
  shared/src/schema/projectObject.ts
Labels: feature

#973 Update frontend to use vite v.5
  .github/workflows/ci.yaml
  e2e/docker-compose.ci.yml
  e2e/tsconfig.json
  frontend/Dockerfile.dev
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: chore

#976 Feature/worktable to year based
  backend/src/router/workTable.ts
  frontend/src/Layout.tsx
  frontend/src/views/WorkTable/Filters/FinancesRangeSelect.tsx
  frontend/src/views/WorkTable/Filters/YearMonthPicker.tsx
  frontend/src/views/WorkTable/Filters/YearPicker.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  frontend/src/views/WorkTable/WorkTableFilters.tsx
  frontend/src/views/WorkTable/columns.tsx
  frontend/vite.config.ts
  shared/src/language/fi.json
  shared/src/schema/workTable.ts
Labels: feature

#982 update manual markdown content and remove one image
  frontend/public/images/talousvalilehti.png
  frontend/src/views/Manual/fi.md
Labels: feature

#983 Fix/bug fixes
  backend/db_migrations/0064_project_object_constraint.sql
  backend/src/router/workTable.ts
  frontend/src/components/DataTable/DataTableRow.tsx
  frontend/src/dayjs.ts
  frontend/src/views/ProjectObject/ProjectObjectForm.tsx
  frontend/src/views/SapReports/index.tsx
  frontend/src/views/WorkTable/Filters/YearPicker.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  frontend/src/views/WorkTable/columns.tsx
  shared/src/schema/projectObject.ts
Labels: fix

#984 Add geoserver user migration
  backend/.eslintrc.cjs
  backend/db_migrations/0065_add_geoserver_view_role.js
Labels: feature

#987 Delete geoserver sql migration
  backend/db_migrations/0065_add_geoserver_view_role.js
Labels: fix

#988 Add geoserver_user migration for local development
  backend/.eslintrc.cjs
  backend/package.json
  backend/src/postMigration.ts
Labels: feature

#985 Add new project object category
  backend/db_migrations/0065_new_project_object_category.sql
Labels: feature

#990 Make sap actuals document type optional
  backend/src/components/sap/dataImport.ts
  backend/src/components/sap/environmentCodeReport.ts
  shared/src/schema/sapActuals.ts
Labels: fix

#992 Fix/bug fixes and refactoring
  backend/src/app.ts
  backend/src/components/project/search.ts
  backend/src/router/projectObject.ts
  frontend/src/components/AsyncJobButton.tsx
  frontend/src/components/forms/SapProjectIdField.tsx
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/Project/Projects.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/SapReports/BlanketContractReportFilters.tsx
  frontend/src/views/SapReports/EnvironmentalCodeReportFilters.tsx
Labels: fix

#997 Feature/project object date validation
  backend/src/components/project/base.ts
  backend/src/router/projectObject.ts
  e2e/test/api/project.test.ts
  e2e/test/api/projectObject.test.ts
  frontend/src/views/ProjectObject/ProjectObjectForm.tsx
  shared/src/language/fi.json
Labels: feature

#999 Change view's year data types to int from double precision
  backend/db_migrations/0066_modify_geoserver_view.sql
Labels: fix

#998 Add new work table functionalities
  backend/src/router/workTable.ts
  frontend/src/views/WorkTable/WorkTableFilters.tsx
  frontend/src/views/WorkTable/columns.tsx
  shared/src/schema/workTable.ts
Labels: feature
