Repository Tampere/Hanna, pull requests merged in 2024-11, with the labels that each got.

#1371 Feature/UI improvements
  frontend/src/components/Charts/FinancesBarChart.tsx
  frontend/src/components/Charts/ProgressBar.tsx
  frontend/src/components/Charts/utils.ts
  frontend/src/components/Map/MapToolbar.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/styles.ts
  frontend/src/views/Project/BudgetTable.tsx
  frontend/src/views/Project/ProjectFinancesCharts.tsx
  frontend/src/views/Task/TaskRow.tsx
  shared/src/language/fi.ts
Labels: feature

#1372 Fix project object search
  backend/src/components/projectObject/search.ts
Labels: fix

#1373 Fix project object search
  backend/src/components/projectObject/search.ts
Labels: fix

#1374 Filter sap actuals with no document type
  backend/src/components/sap/environmentCodeReport.ts
  backend/src/router/sap.ts
Labels: feature

#1380 Fix/map extent setting
  backend/src/components/projectObject/index.ts
  backend/src/components/projectObject/search.ts
  frontend/src/components/Map/DrawMap.tsx
  frontend/src/components/Map/MapControls.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/SearchResultsMap.tsx
  frontend/src/stores/navigationBlocker.tsx
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ResultsMap.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/ProjectObject/ProjectObjectResultsMap.tsx
Labels: fix

#1381 Tweak financial charts styling
  frontend/src/components/Charts/ChartHeader.tsx
  frontend/src/components/Charts/FinancesBarChart.tsx
  frontend/src/views/Project/ProjectFinancesCharts.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinancesCharts.tsx
Labels: feature

#1382 Feature/small tweaks
  backend/db_migrations/0086_remove_redundant_codes.sql
  frontend/src/views/SapReports/index.tsx
Labels: feature

#1386 Remove deprecated db tables
  backend/db_migrations/0087_remove_deprecated_tables.sql
Labels: chore

#1388 Make project and object view form hideable
  frontend/src/components/ExpandButton.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ProjectViewMainContentWrapper.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  shared/src/language/fi.ts
Labels: feature

#1389 Fix other forms disappearing bug while hiding project or object form
  frontend/src/views/Project/ProjectViewMainContentWrapper.tsx
Labels: fix

#1390 Feature/new map features and fixes
  frontend/src/components/Map/DrawMap.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/NoGeomInfoBox.tsx
  frontend/src/components/Map/SearchResultsMap.tsx
  frontend/src/components/Map/mapFunctions.tsx
  frontend/src/components/Map/mapInteractions.ts
  frontend/src/components/Map/styles.ts
  frontend/src/stores/map.ts
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ProjectViewMainContentWrapper.tsx
  frontend/src/views/Project/ResultsMap.tsx
  frontend/src/views/ProjectObject/ProjectObjectResultsMap.tsx
  shared/src/language/fi.ts
Labels: feature

#1270 Update readme and add new dev-build script
  README.md
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  package.json
  scripts/clean_start_dev_environment.sh
Labels: chore

#1387 Chore/update manual expense monitoring
  frontend/public/images/kartan_piirtotoiminnot.png
  frontend/public/images/kuluseuranta.png
  frontend/src/views/Manual/fi.md
Labels: chore

#1392 Tweak no geom infobox position
  frontend/src/components/Map/NoGeomInfoBox.tsx
Labels: feature

#1393 Fix unvisible map for projects with whole municipality area geometry
  frontend/src/components/Map/DrawMap.tsx
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
Labels: fix

#1394 Fix a bug preventing maintenance writer from creating new project
  frontend/src/views/Project/Projects.tsx
Labels: fix

#1398 Fix/bug fixes
  frontend/src/Layout.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/NoGeomInfoBox.tsx
  frontend/src/components/Map/styles.ts
  frontend/src/components/TooltipLinkTab.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObjects.tsx
Labels: fix

#1403 Add possibility to select multiple committees for investment projects
  backend/db_migrations/0088_multiple_committees_selection.sql
  backend/src/components/project/base.ts
  backend/src/components/project/index.ts
  backend/src/components/project/investment.ts
  backend/src/components/project/search.ts
  backend/src/components/projectObject/index.ts
  backend/src/components/projectObject/investment.ts
  backend/src/components/taskQueue/workTableReportQueue.ts
  backend/src/router/project/base.ts
  backend/src/router/project/investment.ts
  backend/src/router/project/maintenance.ts
  backend/src/router/projectObject/investment.ts
  backend/src/router/projectObject/maintenance.ts
  backend/src/router/workTable.ts
  e2e/test/api/financialPermissions.test.ts
  e2e/test/api/generalNotificationPermissions.test.ts
  e2e/test/api/project.test.ts
  e2e/test/api/projectObject.test.ts
  e2e/test/api/projectObjectData.ts
  e2e/test/api/projectPermissions.test.ts
  e2e/test/project.test.ts
  frontend/src/components/forms/CodeSelect.tsx
  frontend/src/components/forms/CommitteeSelect.tsx
  frontend/src/components/forms/CurrencyInput.tsx
  frontend/src/components/forms/MultiSelect.tsx
  frontend/src/components/forms/index.tsx
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/Project/BudgetTable.tsx
  frontend/src/views/Project/BudgetTable/BudgetContentRow.tsx
  frontend/src/views/Project/BudgetTable/CommitteeSelection.tsx
  frontend/src/views/Project/BudgetTable/TotalRow.tsx
  frontend/src/views/Project/BudgetTable/YearTotalRow.tsx
  frontend/src/views/Project/BudgetTable/index.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/Project/ProjectFinances.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinances.tsx
  frontend/src/views/WorkTable/Filters/WorkTableFilters.tsx
  frontend/src/views/WorkTable/WorkTable.tsx
  frontend/src/views/WorkTable/WorkTableSummaryRow.tsx
  frontend/src/views/WorkTable/columns.tsx
  shared/src/language/fi.ts
  shared/src/schema/project/index.ts
  shared/src/schema/projectObject/base.ts
  shared/src/schema/projectObject/investment.ts
  shared/src/schema/workTable.ts
Labels: feature

#1404 Fix faulty imports
  backend/src/components/project/investment.ts
  frontend/src/views/Project/BudgetTable/TotalRow.tsx
  frontend/src/views/Project/BudgetTable/YearTotalRow.tsx
  frontend/src/views/Project/ProjectFinances.tsx
Labels: fix

#1405 Add ordering selector for project object list
  backend/src/components/projectObject/index.ts
  backend/src/router/projectObject/base.ts
  frontend/src/views/ProjectObject/ProjectObjectFinances.tsx
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
  shared/src/language/fi.ts
  shared/src/schema/projectObject/index.ts
Labels: feature

#1406 Fix faulty imports
  backend/src/router/projectObject/base.ts
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
Labels: fix

#1408 Feature/multiple committees selection improvements
  backend/src/components/project/index.ts
  backend/src/components/project/investment.ts
  backend/src/components/projectObject/investment.ts
  backend/src/router/project/investment.ts
  backend/src/router/projectObject/investment.ts
  frontend/src/components/forms/CommitteeChangeAlert.tsx
  frontend/src/components/forms/CommitteeSelect.tsx
  frontend/src/components/forms/CurrencyInput.tsx
  frontend/src/views/Project/BudgetTable/BudgetContentRow.tsx
  frontend/src/views/Project/BudgetTable/CommitteeSelection.tsx
  frontend/src/views/Project/BudgetTable/TotalRow.tsx
  frontend/src/views/Project/BudgetTable/YearTotalRow.tsx
  frontend/src/views/Project/BudgetTable/index.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/Project/ProjectFinances.tsx
  frontend/src/views/Project/ProjectViewWrapper.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  shared/src/language/fi.ts
Labels: feature

#1409 Add project date year shift functionality
  backend/src/components/project/base.ts
  backend/src/components/projectObject/index.ts
  backend/src/router/project/base.ts
  frontend/src/components/SplitButton.tsx
  frontend/src/views/Project/ProjectFinances.tsx
  frontend/src/views/Project/ProjectViewWrapper/ModifyButton.tsx
  frontend/src/views/Project/ProjectViewWrapper/ProjectShiftView.tsx
  frontend/src/views/Project/ProjectViewWrapper/index.tsx
  shared/src/language/fi.ts
Labels: feature

#1419 Add secondary ordering to project object list
  backend/src/components/projectObject/index.ts
Labels: feature

#1420 Fix project object date validation
  backend/src/components/projectObject/index.ts
Labels: fix

#1423 Fix a bug preventing sap project id deletion on investment projects
  frontend/src/views/Project/InvestmentProjectForm.tsx
Labels: fix

#1422 Feature/UI tweaks
  frontend/src/Layout.tsx
  frontend/src/components/Charts/FinancesBarChart.tsx
  frontend/src/components/Map/LayerDrawer.tsx
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/mapFunctions.tsx
  frontend/src/components/Map/mapOptions.tsx
  frontend/src/stores/map.ts
  frontend/src/views/GeneralNotifications/GeneralNotificationList.tsx
  frontend/src/views/Project/BudgetTable/index.tsx
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
  shared/src/language/fi.ts
Labels: feature

#1421 Add worktable date range select constraints
  backend/src/components/projectObject/index.ts
  backend/src/router/projectObject/base.ts
  frontend/src/views/WorkTable/DateRangePicker.tsx
Labels: feature

#1424 Fix geodata buildings url
  frontend/src/components/Map/mapOptions.tsx
Labels: fix
