Repository Tampere/Hanna, pull requests merged in 2024-10, with the labels that each got.

#1310 Add new "target" field to investment project
  backend/db_migrations/0083_new_codes.sql
  backend/src/components/project/investment.ts
  backend/src/components/project/search.ts
  backend/src/router/workTable.ts
  e2e/test/api/project.test.ts
  e2e/test/api/projectObjectData.ts
  e2e/test/api/projectPermissions.test.ts
  frontend/src/Layout.tsx
  frontend/src/components/Fieldset.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/NavigationBlocker.tsx
  frontend/src/stores/navigationBlocker.tsx
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/Project/InvestmentProjectSearch.tsx
  frontend/src/views/Project/ProjectFinances.tsx
  frontend/src/views/Project/ProjectViewWrapper.tsx
  frontend/src/views/Project/SearchControls.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/MaintenanceProjectObjectForm.tsx
  frontend/src/views/WorkTable/Filters/WorkTableFilters.tsx
  shared/src/language/fi.ts
  shared/src/schema/code.ts
  shared/src/schema/project/index.ts
  shared/src/schema/project/investment.ts
  shared/src/schema/workTable.ts
Labels: feature

#1316 Improve project view geometry updating logic
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ProjectViewWrapper.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
Labels: fix

#1318 Fix/bug fixes and UI improvements
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/stores/projectView.ts
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Project/BudgetTable.tsx
  frontend/src/views/Project/DeleteProjectDialog.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/Project/ProjectPermissions.tsx
  frontend/src/views/Project/ProjectViewWrapper.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/MaintenanceProjectObjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  shared/src/language/fi.ts
Labels: fix

#1320 Add feature hover highlighting and new cursor to map
  frontend/src/assets/detailplanClusterPointHover.svg
  frontend/src/assets/investmentClusterPointHover.svg
  frontend/src/assets/maintenanceClusterPointHover.svg
  frontend/src/assets/projectClusterPointHover.svg
  frontend/src/assets/projectObjectClusterPointHover.svg
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/mapInteractions.ts
  frontend/src/components/Map/styles.ts
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/ProjectObject/DeleteProjectObjectDialog.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
Labels: feature

#1321 Feature/new draw tools
  backend/src/components/project/investment.ts
  backend/src/components/project/maintenance.ts
  frontend/src/components/Map/MapToolbar.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/mapInteractions.ts
  frontend/src/components/Map/styles.ts
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  shared/src/language/fi.ts
  shared/src/schema/project/investment.ts
  shared/src/schema/project/maintenance.ts
Labels: feature

#1322 updates to manual contents and images
  frontend/public/images/hankesivun_karttanakyma_toiminnot_nimetty.png
  frontend/public/images/investointiohjelmointi.png
  frontend/public/images/investointiohjelmointi_v2.png
  frontend/public/images/kartan_piirtotoiminnot.png
  frontend/public/images/karttasivu.png
  frontend/public/images/muokkaus_ponnahdus.png
  frontend/public/images/palaa_ylos_painike.png
  frontend/public/images/tallenna_palkki.png
  frontend/src/views/Manual/fi.md
Labels: chore

#1328 Revert "updates to manual contents and images"
  frontend/public/images/hankesivun_karttanakyma_toiminnot_nimetty.png
  frontend/public/images/investointiohjelmointi.png
  frontend/public/images/investointiohjelmointi_v2.png
  frontend/public/images/kartan_piirtotoiminnot.png
  frontend/public/images/karttasivu.png
  frontend/public/images/muokkaus_ponnahdus.png
  frontend/public/images/palaa_ylos_painike.png
  frontend/public/images/tallenna_palkki.png
  frontend/src/views/Manual/fi.md
Labels: chore

#1329 Update user manual and clear manual of old content
  frontend/public/images/hankesivun_karttanakyma_toiminnot_nimetty.png
  frontend/public/images/investointiohjelmointi.png
  frontend/public/images/investointiohjelmointi_v2.png
  frontend/public/images/kartan_piirtotoiminnot.png
  frontend/public/images/karttasivu.png
  frontend/public/images/muokkaus_ponnahdus.png
  frontend/public/images/palaa_ylos_painike.png
  frontend/public/images/tallenna_palkki.png
  frontend/src/views/Manual/fi.md
Labels: chore

#1330 Fix manual image links
  frontend/src/views/Manual/fi.md
Labels: fix

#1331 Feature/project view ux improvements
  backend/src/components/projectObject/index.ts
  e2e/test/api/financialPermissions.test.ts
  frontend/src/components/Map/styles.ts
  frontend/src/components/forms/CurrencyInput.tsx
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Project/BudgetTable.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/Project/ProjectFinances.tsx
  frontend/src/views/Project/ProjectViewWrapper.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/MaintenanceProjectObjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinances.tsx
  frontend/src/views/Task/TaskDialog.tsx
  shared/src/schema/project/index.ts
  shared/src/schema/projectObject/base.ts
  shared/src/schema/projectObject/investment.ts
Labels: feature

#1332 Update minor dependencies
  backend/package-lock.json
  backend/package.json
  e2e/package-lock.json
  e2e/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/patches/@mui+x-data-grid+7.19.0.patch
  shared/package-lock.json
  shared/package.json
Labels: chore

#1337 Add map ux improvements
  frontend/src/components/Map/Map.tsx
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/mapInteractions.ts
  frontend/src/components/Map/styles.ts
  frontend/src/components/forms/CurrencyInput.tsx
  frontend/src/views/Project/ProjectFinances.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinances.tsx
Labels: feature

#1338 Fix form date validation errors
  backend/src/components/project/base.ts
  backend/src/components/projectObject/index.ts
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/MaintenanceProjectObjectForm.tsx
Labels: fix

#1339 Fix and refactor form validation
  frontend/src/components/forms/index.tsx
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/MaintenanceProjectObjectForm.tsx
Labels: feature

#1345 Feature/move rakennuttaja suunnitteluttaja to roles
  backend/db_migrations/0084_new_investment_roles.sql
  backend/src/components/projectObject/index.ts
  backend/src/components/projectObject/investment.ts
  backend/src/components/projectObject/maintenance.ts
  backend/src/components/projectObject/search.ts
  backend/src/components/report/investmentProject.ts
  backend/src/router/workTable.ts
  frontend/src/components/forms/RoleSelect.tsx
  frontend/src/views/ProjectObject/InvestmentProjectObjectForm.tsx
  frontend/src/views/ProjectObject/ProjectObjectFormUserRoles.tsx
  frontend/src/views/WorkTable/Filters/WorkTableFilters.tsx
  frontend/src/views/WorkTable/ProjectObjectUsers.tsx
  frontend/src/views/WorkTable/columns.tsx
  shared/src/schema/code.ts
  shared/src/schema/projectObject/base.ts
  shared/src/schema/projectObject/investment.ts
  shared/src/schema/workTable.ts
Labels: feature

#1346 Feature/map ux improvement
  backend/src/components/project/base.ts
  backend/src/components/project/detailplan.ts
  backend/src/components/project/investment.ts
  backend/src/components/project/maintenance.ts
  backend/src/components/project/search.ts
  backend/src/components/projectObject/index.ts
  backend/src/components/projectObject/investment.ts
  backend/src/components/projectObject/maintenance.ts
  backend/src/components/projectObject/search.ts
  frontend/src/assets/detailPlanClusterPointHover.png
  frontend/src/assets/detailplanClusterPoint.png
  frontend/src/assets/detailplanClusterPoint.svg
  frontend/src/assets/detailplanClusterPointHover.svg
  frontend/src/assets/investmentClusterPoint.png
  frontend/src/assets/investmentClusterPoint.svg
  frontend/src/assets/investmentClusterPointHover.png
  frontend/src/assets/investmentClusterPointHover.svg
  frontend/src/assets/maintenanceClusterPoint.png
  frontend/src/assets/maintenanceClusterPoint.svg
  frontend/src/assets/maintenanceClusterPointHover.png
  frontend/src/assets/maintenanceClusterPointHover.svg
  frontend/src/assets/projectClusterPoint.png
  frontend/src/assets/projectClusterPoint.svg
  frontend/src/assets/projectClusterPointHover.png
  frontend/src/assets/projectClusterPointHover.svg
  frontend/src/assets/projectClusterPointSelected.png
  frontend/src/assets/projectClusterPointSelected.svg
  frontend/src/assets/projectObjectClusterPoint.png
  frontend/src/assets/projectObjectClusterPoint.svg
  frontend/src/assets/projectObjectClusterPointHover.png
  frontend/src/assets/projectObjectClusterPointHover.svg
  frontend/src/assets/projectObjectClusterPointSelected.png
  frontend/src/assets/projectObjectClusterPointSelected.svg
  frontend/src/components/Map/MapWrapper.tsx
  frontend/src/components/Map/mapInteractions.ts
  frontend/src/components/Map/styles.ts
  frontend/src/stores/map.ts
  frontend/src/views/DetailplanProject/DetailplanProject.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ProjectAreaSelectorForm.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/tsconfig.json
Labels: feature

#1347 Fix self intersecting geometries not showing on map
  backend/src/components/project/base.ts
  backend/src/components/projectObject/index.ts
Labels: fix

#1353 Add finances charts view
  backend/src/components/sap/actuals.ts
  backend/src/components/sap/utils.ts
  backend/src/router/sap.ts
  docker/sap-mock/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Charts/ChartHeader.tsx
  frontend/src/components/Charts/FinancesBarChart.tsx
  frontend/src/components/Charts/ProgressBar.tsx
  frontend/src/components/Map/styles.ts
  frontend/src/components/TooltipLinkTab.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ProjectFinancesCharts.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinancesCharts.tsx
  shared/src/language/fi.ts
Labels: feature

#1355 Fix monthly sap actuals fetch and improve finance charts
  backend/src/components/sap/actuals.ts
  backend/src/components/sap/dataImport.ts
  backend/src/router/sap.ts
  frontend/src/components/Charts/FinancesBarChart.tsx
  frontend/src/utils/array.ts
  frontend/src/views/MaintenanceProject/MaintenanceProject.tsx
  frontend/src/views/Project/InvestmentProject.tsx
  frontend/src/views/Project/ProjectFinancesCharts.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinancesCharts.tsx
  shared/src/language/fi.ts
Labels: fix

#1356 Fix all negative value case for finances chart
  frontend/src/components/Charts/FinancesBarChart.tsx
  frontend/src/components/Charts/utils.ts
  frontend/src/views/Project/ProjectFinancesCharts.tsx
  frontend/src/views/ProjectObject/ProjectObjectFinancesCharts.tsx
Labels: fix

#1357 Improve test performance and reduce flakiness
  e2e/test/api/code.test.ts
  e2e/test/api/financialPermissions.test.ts
  e2e/test/api/generalNotification.test.ts
  e2e/test/api/generalNotificationPermissions.test.ts
  e2e/test/api/project.test.ts
  e2e/test/api/projectObject.test.ts
  e2e/test/api/projectPermissions.test.ts
  e2e/test/api/sap.test.ts
  e2e/test/project.test.ts
  e2e/test/workTable.test.ts
  e2e/utils/fixtures.ts
  e2e/utils/page.ts
Labels: chore

#1358 Chore/update deps 20241028
  backend/package-lock.json
  backend/package.json
  e2e/package-lock.json
  e2e/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/patches/@mui+x-data-grid+7.22.0.patch
  shared/package-lock.json
  shared/package.json
Labels: chore

#1369 Remove task from data model and fetch task info from sap
  backend/db_migrations/0085_remove_tasks.sql
  backend/src/components/sap/actuals.ts
  backend/src/components/sap/dataImport.ts
  backend/src/router/index.ts
  backend/src/router/sap.ts
  backend/src/router/task.ts
  docker/sap-mock/mock-server.clj
  frontend/src/views/Project/BudgetTable.tsx
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/Task/DeleteTaskDialog.tsx
  frontend/src/views/Task/TaskDialog.tsx
  frontend/src/views/Task/TaskForm.tsx
  frontend/src/views/Task/TaskList.tsx
  frontend/src/views/Task/TaskRow.tsx
  frontend/src/views/Task/Tasks.tsx
  shared/src/language/fi.ts
  shared/src/schema/task.ts
Labels: feature

#1370 Feature/UI tweaks
  frontend/src/assets/projectObjectPoint.svg
  frontend/src/assets/projectObjectPointSmall.png
  frontend/src/components/Charts/ChartHeader.tsx
  frontend/src/components/Charts/FinancesBarChart.tsx
  frontend/src/components/Charts/utils.ts
  frontend/src/components/HelpTooltip.tsx
  frontend/src/components/Map/mapInteractions.ts
  frontend/src/components/Map/styles.ts
  frontend/src/components/forms/UserSelect.tsx
  frontend/src/stores/map.ts
  frontend/src/views/DetailplanProject/DetailplanProjectForm.tsx
  frontend/src/views/MaintenanceProject/MaintenanceProjectForm.tsx
  frontend/src/views/Project/InvestmentProjectForm.tsx
  frontend/src/views/Task/TaskList.tsx
  shared/src/language/fi.ts
Labels: feature
