Repository Tampere/Hanna, pull requests merged in 2025-03, with the labels that each got.

#1516 Fix cluster feature coloring
  frontend/src/components/Map/styles.ts
Labels: fix

#1518 Fix map cluster coloring
  frontend/src/components/Map/styles.ts
Labels: fix

#1520 Chore/update deps 20250313
  backend/package-lock.json
  backend/package.json
  backend/src/components/mail/index.ts
  e2e/package-lock.json
  e2e/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/patches/@mui+x-data-grid+7.27.3.patch
  shared/package-lock.json
  shared/package.json
Labels: chore

#1517 Added ability to add images to general notifications
  backend/db_migrations/0092_add_file_table.sql
  backend/src/app.ts
  backend/src/components/file/index.ts
  backend/src/components/generalNotification/index.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/TextEditor/MenuBar.tsx
  frontend/src/components/TextEditor/index.tsx
  frontend/src/views/GeneralNotifications/GeneralNotificationCard.tsx
  frontend/src/views/GeneralNotifications/GeneralNotificationList.tsx
  frontend/src/views/Management/GeneralNotifications/GeneralNotificationTextEditor.tsx
  package-lock.json
  package.json
  shared/src/language/fi.ts
Labels: feature

#1524 Add possibility to order project object listing by lifecycle state
  backend/src/components/projectObject/index.ts
  frontend/src/components/icons/Complete.tsx
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
  shared/src/language/fi.ts
  shared/src/schema/projectObject/index.ts
Labels: feature

#1525 Tweak project object list ordering logic
  backend/src/components/projectObject/index.ts
Labels: feature

#1535 Fix overflowing text content in project and object view
  frontend/src/views/ProjectObject/ProjectObject.tsx
  frontend/src/views/ProjectObject/ProjectObjectList.tsx
Labels: fix
